"""Behave steps for tests/bdd/enrichment/instagram-avatar-edge-color.feature.

Reuses the harness `instagram_profile_photo_hero_steps.py` already builds — the
REAL `VenueProfilePhotoService` over the REAL `VenueRepository`, the REAL
`VenueMediaStore` (only its boto3 client faked) and the REAL projector — and
adds only what the edge colour needs. Behave loads every module under
`steps/`, so the existing Given/When/Then phrasings are in scope here and are
NOT redefined (behave rejects a duplicate outright).

Two things are deliberate:

- The avatars are REAL encoded images, generated by Pillow with a known flat
  border. Asserting `#004A9D` came back out means production code actually
  decoded pixels; a hand-written stub colour would assert nothing.
- The backfill's fetches go through the SAME `_FakeImageFetcher` the scrape
  path uses, programmed against the row's own **CDN URL**. That is what lets
  "the backfill read the photo from its stored CDN URL" be asserted as an
  observable call rather than inferred, and what makes "no profile scrape is
  requested at all" a statement about the billed boundary.

Imports of the feature's own module are lazy and tolerant: during the true-RED
run `app.services.image_edge_color` does not exist yet, and the scenarios must
fail on observable state (no colour on the row, no colour in Redis) rather than
on an ImportError raised inside a Given.
"""
from __future__ import annotations

import hashlib
import io
import json
from datetime import datetime, timezone

from behave import given, when, then  # type: ignore[import-untyped]

from app.config import settings

from instagram_profile_photo_hero_steps import (  # type: ignore[import-not-found]
    _boundaries,
    _override_setting,
    _puts,
    _redis_photo,
    _run,
    _service,
    _summary,
    _seed_venue,
)

_PROFILE_PHOTO_TABLE = "instagram.profile_photo"


# ── real image bytes with a known border ────────────────────────────────────


def _avatar_png(border_hex: str, *, size: int = 100) -> bytes:
    """A square avatar whose outer frame is exactly `border_hex`.

    Square, because that is what an Instagram avatar is, and what makes the
    LEFT and RIGHT columns the strips a `contain` fit into a wider box would
    letterbox. PNG rather than JPEG so the border survives round-tripping
    without ringing — the scenario is about which colour is dominant, not about
    the codec's tolerance.
    """
    from PIL import Image

    border = tuple(int(border_hex[i:i + 2], 16) for i in (1, 3, 5))
    # The contrasting centre deliberately DOMINATES the image by area (~64%),
    # so a sampler that read the whole image instead of only the letterboxed
    # vertical strips would return the centre colour and every scenario here
    # would fail. Sabotage-verified: widening the crop to the full image turns
    # this feature red.
    centre = (255 - border[0], 255 - border[1], 255 - border[2])
    img = Image.new("RGB", (size, size), border)
    inner = max(1, size // 10)
    img.paste(Image.new("RGB", (size - 2 * inner, size - 2 * inner), centre), (inner, inner))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _row(context, vid: str):
    return context.rds_store.enrichment.get(_PROFILE_PHOTO_TABLE, {}).get(vid)


def _payload(context, vid: str) -> dict:
    row = _row(context, vid)
    assert row is not None, f"no profile photo row exists for {vid}"
    return row.get("payload") or {}


def _cdn_url(vid: str, data: bytes) -> tuple[str, str]:
    content_hash = hashlib.sha256(data).hexdigest()
    key = f"venue-profile-photos/{vid}/{content_hash[:16]}.jpg"
    return key, f"{settings.media_cdn_base_url.rstrip('/')}/{key}"


# ── Given: the scrape returns a real avatar ─────────────────────────────────


@given('the profile scrape returns an avatar whose border is "{border}"')
def step_scrape_returns_avatar(context, border):
    from instagram_profile_photo_hero_steps import _program_pic  # lazy: same package

    vid = context.last_venue_id
    context.picture_bytes = _avatar_png(border)
    context.expected_edge_color = border
    _program_pic(context, vid, context.picture_bytes, content_type="image/png")


@given("the profile scrape returns a picture whose bytes are not a decodable image")
def step_scrape_returns_undecodable(context):
    from instagram_profile_photo_hero_steps import _program_pic

    vid = context.last_venue_id
    # A perfectly valid JPEG content-type carrying bytes no decoder accepts.
    # This is the shape a truncated CDN response actually takes, and the photo
    # must still be STORED — the colour is the only thing that may be missing.
    context.picture_bytes = b"\xff\xd8\xff\xe0not-really-a-jpeg"
    _program_pic(context, vid, context.picture_bytes)


@given("the profile scrape returns the same avatar again")
def step_scrape_returns_same_avatar(context):
    from instagram_profile_photo_hero_steps import _program_pic

    vid = context.last_venue_id
    _program_pic(
        context, vid, context.stored_photo_bytes[vid], content_type="image/png",
    )


# ── Given: rows that already exist (the backfill's input) ───────────────────


def _seed_row(context, vid: str, data: bytes, *, edge_color=None) -> str:
    """Seed a stored photo row the way the service would have written it, and
    program the image fetcher against its CDN URL so the backfill can read it
    back the way production will — over HTTPS, never from S3."""
    if getattr(context, "handles", None) is None:
        context.handles = {}
    if getattr(context, "stored_photo_bytes", None) is None:
        context.stored_photo_bytes = {}
    if getattr(context, "seeded_venues", None) is None:
        context.seeded_venues = []
    if _row(context, vid) is None and vid not in context.seeded_venues:
        _seed_venue(context, vid)
        context.seeded_venues.append(vid)

    key, url = _cdn_url(vid, data)
    payload = {
        "venue_id": vid,
        "instagram_handle": context.handles.get(vid),
        "photo_url": url,
        "s3_key": key,
        "content_hash": hashlib.sha256(data).hexdigest(),
        "content_type": "image/png",
        "byte_size": len(data),
        "fetched_at": datetime.now(timezone.utc).isoformat(),
    }
    if edge_color is not None:
        payload["edge_color"] = edge_color
    context.rds_store.upsert_enrichment(
        _PROFILE_PHOTO_TABLE, vid, payload, history=False,
    )
    context.stored_photo_bytes[vid] = data
    context.last_venue_id = vid

    _, fetcher = _boundaries(context)
    fetcher.program(url, (data, "image/png"))
    return url


@given('venue "{vid}" has a stored profile photo with no edge colour and a border of "{border}"')
def step_row_without_edge_color(context, vid, border):
    _seed_row(context, vid, _avatar_png(border))
    context.expected_edge_color = border


@given('venue "{vid}" has a stored profile photo whose edge colour is "{border}"')
def step_row_with_edge_color(context, vid, border):
    _seed_row(context, vid, _avatar_png("#000000"), edge_color=border)


@given('fetching the stored photo for venue "{vid}" fails')
def step_fetch_fails(context, vid):
    _, fetcher = _boundaries(context)
    url = _payload(context, vid)["photo_url"]
    fetcher.program(url, RuntimeError("BDD: CDN unreachable"))


@given("the per-run profile photo cap is {count:d}")
def step_per_run_cap(context, count):
    _override_setting(context, "instagram_profile_photo_max_venues_per_run", count)


# ── When ────────────────────────────────────────────────────────────────────


@when("the edge-colour cost estimate is requested")
def step_edge_color_estimate(context):
    service = _service(context)
    estimate = getattr(service, "estimate", None) if service is not None else None
    context.estimate = estimate({"mode": "edge_color"}) if estimate is not None else {}


@when('the profile photo job is triggered with the mode "{mode}"')
def step_trigger_invalid_mode(context, mode):
    """Capture the rejection rather than let it escape: the scenario asserts
    BOTH that the trigger was refused AND that nothing was processed, and an
    exception escaping the When would make the second half unreachable."""
    service = _service(context)
    context.mode_rejection = None
    if service is None:
        return
    try:
        context.profile_photo_summary = _run(service.run({"mode": mode}))
    except Exception as exc:  # the rejection is the behaviour under test
        context.mode_rejection = exc


# ── Then: the colour on the row and in the projection ───────────────────────


@then('the profile photo row for venue "{vid}" records the edge colour "{border}"')
def step_row_records_edge_color(context, vid, border):
    actual = _payload(context, vid).get("edge_color")
    assert actual == border, (
        f"{vid}: expected edge_color {border!r}, got {actual!r}"
    )


@then('the profile photo row for venue "{vid}" records no edge colour')
def step_row_records_no_edge_color(context, vid):
    actual = _payload(context, vid).get("edge_color")
    assert not actual, f"{vid}: expected no edge_color, got {actual!r}"


@then('the Redis key "{key}" carries the edge colour "{border}"')
def step_redis_carries_edge_color(context, key, border):
    raw = context.fake_redis.get(key)
    assert raw, f"no projected value at {key}"
    actual = json.loads(raw).get("edge_color")
    assert actual == border, f"{key}: expected {border!r}, got {actual!r}"


@then('the Redis key "{key}" carries no edge colour')
def step_redis_carries_no_edge_color(context, key):
    raw = context.fake_redis.get(key)
    assert raw, f"no projected value at {key}"
    actual = json.loads(raw).get("edge_color")
    assert not actual, f"{key}: expected no edge colour, got {actual!r}"


@then("exactly {count:d} profile photo row carries an edge colour")
@then("exactly {count:d} profile photo rows carry an edge colour")
def step_count_rows_with_edge_color(context, count):
    rows = context.rds_store.enrichment.get(_PROFILE_PHOTO_TABLE, {})
    actual = sum(1 for r in rows.values() if (r.get("payload") or {}).get("edge_color"))
    assert actual == count, f"expected {count} coloured rows, got {actual}"


# ── Then: the cost guarantees ───────────────────────────────────────────────


@then("no profile scrape is requested at all")
def step_no_scrape_at_all(context):
    apify, _ = _boundaries(context)
    assert apify.calls == [], (
        "the edge-colour backfill billed an Apify scrape; it must read the "
        f"photo it already has over the CDN. Calls: {apify.calls}"
    )


@then('no image is fetched for venue "{vid}"')
def step_no_image_fetched(context, vid):
    _, fetcher = _boundaries(context)
    row = _row(context, vid)
    url = (row.get("payload") or {}).get("photo_url") if row else None
    assert url not in fetcher.calls, f"{vid}: unexpected fetch of {url}"


@then('the image for venue "{vid}" was fetched from its stored CDN URL')
def step_image_fetched_from_cdn(context, vid):
    _, fetcher = _boundaries(context)
    url = _payload(context, vid)["photo_url"]
    assert url.startswith(settings.media_cdn_base_url.rstrip("/")), (
        f"{vid}: stored photo_url is not a CDN URL: {url!r}"
    )
    assert url in fetcher.calls, (
        f"{vid}: the backfill did not fetch {url}; fetched {fetcher.calls}"
    )
    assert _puts(context) == [], "the backfill uploaded an object"


@then('the profile photo row for venue "{vid}" is otherwise unchanged')
def step_row_otherwise_unchanged(context, vid):
    """Everything but `edge_color` must survive the backfill byte-for-byte.

    `content_hash` and `instagram_handle` are the load-bearing pair: they are
    what `_has_current_photo` reads, so rewriting either would make the next
    scheduled backfill re-buy an Apify scrape for every row this job touched.
    """
    data = context.stored_photo_bytes[vid]
    key, url = _cdn_url(vid, data)
    payload = _payload(context, vid)
    expected = {
        "venue_id": vid,
        "photo_url": url,
        "s3_key": key,
        "content_hash": hashlib.sha256(data).hexdigest(),
        "byte_size": len(data),
        "instagram_handle": context.handles.get(vid),
    }
    for field, want in expected.items():
        assert payload.get(field) == want, (
            f"{vid}.{field}: expected {want!r}, got {payload.get(field)!r}"
        )
    assert payload.get("edge_color"), f"{vid}: the backfill recorded no colour"


# ── Then: estimate, cap, mode ───────────────────────────────────────────────


@then("the edge-colour estimate reports {count:d} venue to process")
@then("the edge-colour estimate reports {count:d} venues to process")
def step_edge_color_estimate_count(context, count):
    service = _service(context)
    estimate = getattr(service, "estimate", None) if service is not None else None
    result = getattr(context, "estimate", None)
    if result is None or not result:
        result = estimate({"mode": "edge_color"}) if estimate is not None else {}
    actual = result.get("venues_to_process", result.get("venues_to_scrape"))
    assert actual == count, f"expected {count} venues to process, got {actual!r}"


@then("the run summary reports {count:d} deferred venue")
@then("the run summary reports {count:d} deferred venues")
def step_deferred_count(context, count):
    actual = _summary(context).get("deferred")
    assert actual == count, f"expected {count} deferred, got {actual!r}"


@then("the trigger is rejected as an invalid mode")
def step_trigger_rejected(context):
    """Rejected, whichever shape the rejection takes.

    `run()` refuses BEFORE selection and reports the terminal status
    `invalid_mode` (a background job must not explode into APScheduler), while
    `estimate()` raises `InvalidProfilePhotoMode` outright. Both are the same
    behaviour under test — the mode was not silently resolved to a default —
    so the step accepts either and rejects anything else.
    """
    exc = getattr(context, "mode_rejection", None)
    if exc is not None:
        assert type(exc).__name__ == "InvalidProfilePhotoMode", (
            f"expected InvalidProfilePhotoMode, got {type(exc).__name__}: {exc}"
        )
        return
    summary = _summary(context)
    assert summary.get("status") == "invalid_mode", (
        "an unknown mode was accepted instead of rejected; run status was "
        f"{summary.get('status')!r}"
    )
    assert summary.get("venues_selected", 0) == 0, (
        "a rejected mode still selected venues"
    )
